name: Dump
on: push
jobs:
    dump:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: ./.github/workflows/actions/dump/
          id: dump
          with:
            enable-context: "true"
        - run: echo "${DATE}"
          env:
            DATE: ${{ steps.dump.outputs.dumped-date }}