name: Manual
on:
    workflow_dispatch:
        inputs:
            greeting:
                description: 'Greeting to display'
                required: true
                default: 'Hello'
                type: string
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ inputs.greeting }}, world!"